### ISSUE TITLE
Azure: Add Availability Zone support

### ISSUE THREAD

**Issue by dkistner** [gardener/machine-controller-manager#332]
To support also `Machines` in Availability zones on Azure the Machine-Controller-Manager need to be able to deploy, bootstrap and manage Azure machines which are not assigned to an Azure AvailabilitySet.

Basically the `AzureMachineClass` resource need a field to configure a zone.
All `Machines` which reference an `AzureMachineClass` with a zone configuration should be deployed into the zone. MachineClasses which have a zone configuration shouldn't have an AvailabilitySet configuration.
This is an example how the `AzureMachineClass` could look like.
```yaml
apiVersion: machine.sapcloud.io/v1alpha1
kind: AzureMachineClass
metadata:
  name: test-machineclass-zone
  namespace: test
spec:
  location: westeurope
  resourceGroup: test
  secretRef: ...
  subnetInfo: ...
  tags: ...
  properties:
    zone: 1
    hardwareProfile: ...
    osProfile: ...
    storageProfile: ...
```

We still want to support `Machines` in an AvailabilitySet. That means the existing configuration needs to be supported too.
```yaml
apiVersion: machine.sapcloud.io/v1alpha1
kind: AzureMachineClass
metadata:
  name: test-machineclass-av-set
  namespace: test
spec:
  location: westeurope
  resourceGroup: test
  secretRef: ...
  subnetInfo: ...
  tags: ...
  properties:
    availabilitySet:
      id: /subscriptions/my-subscription-id/resourceGroups/test/providers/Microsoft.Compute/availabilitySets/test-workers
    hardwareProfile: ...
    osProfile: ...
    storageProfile: ...
```

In any case it should't be possible to use Availability Zone and AvailabilitySet in parallel. Probably we should throw an error when a user tries to create a `AzureMachineClass` with both configured or if a `Machine` reference such a `AzureMachineClass`.

Is related to: https://github.com/gardener/gardener-extensions/issues/135

cc @AndreasBurger, @MSSedusch, @rfranzke
