### ISSUE TITLE
Cluster upgrades may cause downtime for workloads with multiple AZs

### ISSUE THREAD

**Issue by georgi-lozev** [gardener/machine-controller-manager#400]
Hey friends.

This is not the typical enhancement request, but still it's a strange behaviour we observed while using cluster managed by Gardener, so I think it's worth sharing.

**Description of the problematic behaviour observed**
We have a relatively small cluster running on GCP with worker nodes distributed over 3 AZs.

Here is the worker setup:
```yaml
      workers:
        - name: worker-c92jz
          machineType: n1-standard-4
          machineImage:
            name: coreos
            version: 2135.6.0
          autoScalerMin: 3
          autoScalerMax: 6
          maxSurge: 1
          maxUnavailable: 0
          volumeType: pd-standard
          volumeSize: 50Gi
      zones:
        - us-west2-a
        - us-west2-b
        - us-west2-c
```

Currently we have 3 worker nodes, 1 node per AZ and our workloads have `PodDisruptionBudget`, `PodAffinity` and `HorizontalPodAutoscaler` configured.

When we roll out a new k8s version to the cluster we observe a downtime of the workloads running on top. The behaviour we see is that all 3 worker nodes seem to start updating all at the same time and in parallel. 

**What would you like to be added**:
Is it possible to alter this behaviour and not trigger a parallel deploy for all zones, but do it one by one or at some configurable value/`%`. Pretty much the same as when we have in a single zone cluster.
If it's not possible at least have it explicitly stated and document what are the preferred adjustments that needs to be done in order to prevent similar misinterpretations from users in future.
The mitigation mechanism we thought may help is that if we increase the nodes to be at least 2 per zone and also scale out our pods to distribute a bit more evenly between the nodes. Any recommendations from your side are welcome.
