### ISSUE TITLE
Strange reason in `Available` condition in MachineDeployment

### ISSUE THREAD

**Issue by rfranzke** [gardener/machine-controller-manager#458]
**What happened**:
The conditions of a healthy `MachineDeployment` look like this:

```yaml
    conditions:
    - lastTransitionTime: "2020-04-29T11:36:41Z"
      lastUpdateTime: "2020-04-29T11:36:41Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
```

If it is scaling up, for example, it looks like this:

```yaml
    conditions:
    - lastTransitionTime: "2020-04-29T11:34:49Z"
      lastUpdateTime: "2020-04-29T11:34:49Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
```

Shouldn't the reason be `MinimumReplicasAvailable` here as well so that the `status=False` makes sense?
