### ISSUE TITLE
MachineDeployment with outdated status.unavailableReplicas value

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#512]
**What happened**:
A machine deployment with an outdated value for `status.unavailableReplicas` was found in the cluster. The value of this was 13 when there no unavailable machines for the machine deployment. 

**What you expected to happen**:
I would not expect such inconsistent values in the machine deployment status

**How to reproduce it (as minimally and precisely as possible)**:
Not sure

**Anything else we need to know**:

Status of CRs.

machine deployment status 

```
status:
  availableReplicas: 12
  conditions:
  - lastTransitionTime: "2020-09-16T23:39:18Z"
    lastUpdateTime: "2020-09-16T23:39:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 89
  readyReplicas: 12
  replicas: 12
  unavailableReplicas: 13
  updatedReplicas: 12
```

machine set status
```
status:
    availableReplicas: 12
    fullyLabeledReplicas: 12
    lastOperation:
      lastUpdateTime: null
    observedGeneration: 38
    readyReplicas: 12
    replicas: 12
```

**Environment**:
/platform aws
