### ISSUE TITLE
prefer-no-schedule taint sticks forever if oldMS --> newMS --> oldMS

### ISSUE THREAD

**Issue by RiRa12621** [gardener/machine-controller-manager#989]
**How to categorize this issue?**
/area robustness
/kind bug
/priority 3

**What happened**:
a `machineSet` keeps the taint `prefer-no-schedule` forever

**What you expected to happen**:
the taint is removed

**How to reproduce it (as minimally and precisely as possible)**:
have a machienset with rolling update strategy. have a worker definition like so

```
      - cri:
          name: containerd
        name: standard-16
        machine:
          type: n2-standard-16
          image:
            name: ubuntu
            version: 22.0.4
          architecture: amd64
        maximum: 10
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: pd-standard
          size: 800Gi
        zones:
          - europe-west1-b
        systemComponents:
          allow: true
```

change the worker image

```
      - cri:
          name: containerd
        name: standard-16
        machine:
          type: n2-standard-16
          image:
            name: flatcar
            version: 9999.9.9
          architecture: amd64
        maximum: 10
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: pd-standard
          size: 800Gi
        zones:
          - europe-west1-b
        systemComponents:
          allow: true
```

Wait for the new machineset to be created. 
Change the worker definition back to what it was before:

```
      - cri:
          name: containerd
        name: standard-16
        machine:
          type: n2-standard-16
          image:
            name: ubuntu
            version: 22.0.4
          architecture: amd64
        maximum: 10
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: pd-standard
          size: 800Gi
        zones:
          - europe-west1-b
        systemComponents:
          allow: true
```
The "new" machineset will be deleted, the old one will be kept, but tainted, resulting in the machines to be tainted.

**Environment**:

:
- Others:
machine-controller-manager:v0.53.0
